apiVersion: v1
kind: ServiceAccount
metadata:
  name: sovereignpr
  namespace: sovereignpr
  labels:
    app: sovereignprmanager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sovereignpr-role
  namespace: sovereignpr
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sovereignpr-rolebinding
  namespace: sovereignpr
subjects:
- kind: ServiceAccount
  name: sovereignpr
  namespace: sovereignpr
roleRef:
  kind: Role
  name: sovereignpr-role
  apiGroup: rbac.authorization.k8s.io
