apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sovereignty-system

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: sovereignty-architecture
  app.kubernetes.io/managed-by: kustomize
