apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sovereignty-system

bases:
  - ../../base

replicas:
  - name: sovereignty-core
    count: 5

patchesStrategicMerge:
  - replica-patch.yaml

commonLabels:
  environment: production
